[package]
name = "weakly_typed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
convert = "0.2.0"
num = "0.4.0"

[[bin]]
name = "weakly_typed"
path = "main.rs"
